# Generated by Django 2.0.5 on 2018-05-05 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0010_auto_20180505_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='height',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='inputTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 15, 44, 50, 535250)),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='weight',
            field=models.FloatField(max_length=10),
        ),
    ]
