# Generated by Django 2.0.5 on 2018-05-05 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0011_auto_20180505_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 16, 2, 35, 40262), null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='userId',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
