# Generated by Django 2.0.5 on 2018-05-05 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0013_auto_20180505_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=3, null=True)),
                ('password', models.CharField(max_length=1)),
                ('userType', models.CharField(max_length=3)),
                ('inputTime', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 18, 10, 48, 419110), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 18, 10, 48, 419110), null=True),
        ),
    ]
