# Generated by Django 2.0.5 on 2018-05-05 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0016_auto_20180505_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 19, 9, 45, 226923), null=True),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='userId',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logindata',
            name='userType',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 19, 9, 45, 226923), null=True),
        ),
    ]
