# Generated by Django 2.0.5 on 2018-05-05 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0018_auto_20180505_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 19, 21, 28, 611661), null=True),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='userId',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 19, 21, 28, 611661), null=True),
        ),
    ]
