# Generated by Django 2.0.5 on 2018-05-05 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0019_auto_20180505_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 19, 43, 23, 230299), null=True),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='userType',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 19, 43, 23, 229299), null=True),
        ),
    ]
