# Generated by Django 2.0.5 on 2018-05-05 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0020_auto_20180505_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=10)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('race', models.CharField(blank=True, max_length=10, null=True)),
                ('diabetes', models.CharField(blank=True, max_length=10, null=True)),
                ('hypertension', models.CharField(blank=True, max_length=10, null=True)),
                ('cancer', models.CharField(blank=True, max_length=10, null=True)),
                ('chronicAthens', models.CharField(blank=True, max_length=10, null=True)),
                ('heartDisease', models.CharField(blank=True, max_length=10, null=True)),
                ('inputTime', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 20, 18, 5, 609791), null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginData',
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 20, 18, 5, 609791), null=True),
        ),
    ]
