# Generated by Django 2.0.5 on 2018-05-05 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0024_auto_20180505_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recId', models.CharField(max_length=10)),
                ('recommendation', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 21, 35, 1, 499839), null=True),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 21, 35, 1, 499839), null=True),
        ),
        migrations.AlterField(
            model_name='registerdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 21, 35, 1, 499839), null=True),
        ),
    ]
