# Generated by Django 2.0.5 on 2018-05-05 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0026_auto_20180505_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientData',
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 21, 43, 23, 565428), null=True),
        ),
        migrations.AlterField(
            model_name='registerdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 21, 43, 23, 565428), null=True),
        ),
    ]
