# Generated by Django 2.0.5 on 2018-05-05 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0028_auto_20180505_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='riskLevel',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 22, 43, 49, 483958), null=True),
        ),
        migrations.AlterField(
            model_name='registerdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 22, 43, 49, 482958), null=True),
        ),
    ]
