# Generated by Django 2.0.5 on 2018-05-06 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoPage', '0031_auto_20180505_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=10, null=True)),
                ('wbc', models.CharField(blank=True, max_length=10, null=True)),
                ('rbc', models.CharField(blank=True, max_length=10, null=True)),
                ('hgb', models.CharField(blank=True, max_length=10, null=True)),
                ('hct', models.CharField(blank=True, max_length=10, null=True)),
                ('mcv', models.CharField(blank=True, max_length=10, null=True)),
                ('inputTime', models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 6, 2, 35, 57, 516852), null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='riskLevel',
        ),
        migrations.AddField(
            model_name='registerdata',
            name='riskLevel',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 6, 2, 35, 57, 516852), null=True),
        ),
        migrations.AlterField(
            model_name='registerdata',
            name='inputTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 6, 2, 35, 57, 516852), null=True),
        ),
    ]
